---

## gpg: directory `/root/.gnupg' created
## gpg: new configuration file `/root/.gnupg/gpg.conf' created
## gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
## gpg: keyring `/root/.gnupg/pubring.gpg' created
## gpg: /root/.gnupg/trustdb.gpg: trustdb created
# - name: Make sure .gnupg/gpg.conf exists to avoid failure
# Use gpg --list-config as a workaround.

- name: Import PGP keys
  shell: gpg --list-config && gpg --recv-keys {{ item.value | join(" ") }}
  changed_when: (
                 "imported:" in import_gpg_keys_gpg_cmd.stderr or
                 "new subkeys:" in import_gpg_keys_gpg_cmd.stderr or
                 "new signatures:" in import_gpg_keys_gpg_cmd.stderr
                )
  register: import_gpg_keys_gpg_cmd
  sudo: yes
  sudo_user: "{{ item.key }}"
  with_dict: pgp_keys
