---

- include: import_pgp_key_list.yml pgp_keys={{ import_pgp_keys }}
- include: import_pgp_key_list.yml pgp_keys={{ import_pgp_keys_group }}
- include: import_pgp_key_list.yml pgp_keys={{ import_pgp_keys_host }}
